### ISSUE TITLE
multiaddprocess.php / addDetails function does not check for duplicates for Range addition

### ISSUE THREAD

**Issue by sloyless** [xebix78/comicdb#13]
If you add a range of issues, submit, and then hit refresh on the success page the same issues are added to the database again.

**Comment by asanchez78** [comment]
Making the combination of user_id and comic_id unique in the users_comics table should take care of this. I made the change and saved a new sql file, but we'll still need to catch the error in code.

**Comment by sloyless** [comment]
This should now be integrated into #33
