### ISSUE TITLE
Change $allowRegistration to "yes"

### ISSUE THREAD

**Issue by Alexisback** [xebix78/comicdb#132]
sorry, I'm not a programmer, I'm in the beginning with the PHP, here it says to set $ allowregistration to "yes", but in the code it is set to true 
`<?php
	require_once('../views/head.php');
	require_once(__ROOT__.'/classes/Registration.php');
	$registration = new Registration();
	$allowRegistration = true;
	if ($allowRegistration != true) {
		$messageNum = 53;
	}
	// show potential errors / feedback (from registration object)
	if (isset ( $registration )) {
		if ($registration->errors) {
			foreach ( $registration->errors as $error ) {
				$errorMessage .= $error;
			}
			$isError = true;
		}
		if ($registration->messages) {
			foreach ( $registration->messages as $message ) {
				$successMessage .= $message;
			}
			$isRegistered = true;
		}
	}
?>`

**Comment by asanchez78** [comment]
Honestly, this code is really bad. I'm a little embarrassed that anyone is actually looking at it. I'm currently working on a complete rewrite of this whole thing using a REST API backend. At any rate, I changed the wording of the README.
