### ISSUE TITLE
Add Publisher field to series table

### ISSUE THREAD

**Issue by sloyless** [xebix78/comicdb#16]
Need to start extending the collection to more than Marvel!

**Comment by sloyless** [comment]
This will probably need to be preconfigured on our end with all of the current publishers, plus an option to add a new publisher (maybe by admin only?)

**Comment by sloyless** [comment]
Added the following publishers as choices in the dropdown:
- Marvel Comics
- DC Comics
- Image Comics
- Dark Horse Comics
- Valiant Comics

Set _Marvel_ as the default choice. (for now)

**Comment by sloyless** [comment]
Added the logos of the publishers and included them in the publisher name in the series meta bar on the `single_issue.php` and `issues.php` pages.

Haven't quite decided how to show the logos on the main index yet...

**Comment by sloyless** [comment]
<img width="371" alt="screen shot 2016-01-19 at 11 12 06 am" src="https://cloud.githubusercontent.com/assets/4803197/12426098/87ce7488-be9d-11e5-8be4-3a24d36225af.png">

**Comment by sloyless** [comment]
<img width="343" alt="screen shot 2016-01-19 at 11 12 54 am" src="https://cloud.githubusercontent.com/assets/4803197/12426117/9c16b842-be9d-11e5-9918-ec009a14898e.png">

**Comment by sloyless** [comment]
@asanchez78 over to you for the database work!

**Comment by asanchez78** [comment]
Finished with PR #39
