### ISSUE TITLE
Wikiaadd.php doesn’t check for duplicates

### ISSUE THREAD

**Issue by sloyless** [xebix78/comicdb#19]
A user _should_ be able to add more than one issue of a comic to their collection, but we need to represent it differently and prevent it adding more than once.

**Comment by sloyless** [comment]
Message: You've already added that issue to your collection. Do you wish to add another copy to your collection?

**Comment by sloyless** [comment]
Perquisites:
- [ ] #20 
- [ ] #21

**Comment by asanchez78** [comment]
Added quantity column to users_comics. The default value in the database is "1".

**Comment by sloyless** [comment]
Closing this as everything is moved to `add.php`
