### ISSUE TITLE
Add datestamp to user accounts and users_comics

### ISSUE THREAD

**Issue by sloyless** [xebix78/comicdb#96]
We can add the datestamp to `users_meta` for the user account creation, but need to add a new field to the `users_comics` table and have it auto generate the date when entered.

**Comment by sloyless** [comment]
User table meta_key name value: `account_created`

users_comics field name: `date_added`

**Comment by asanchez78** [comment]
created date_added column with the type "TIMESTAMP". The default when creating a new row is the current time.

`ALTER TABLE users_comics ADD date_added TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP AFTER originalPurchase;`
